### ISSUE TITLE
config.json does not respect base_url 

### ISSUE THREAD

**Issue by Madic-** [alerta/alerta-webui#240]
**Issue Summary**
When setting BASE_URL to e.g. /alerta, config.json still gets loaded from /

**Environment**
- OS: Linux
- API version: 7.4.0
- Deployment: Docker with Traefik as reverse proxy
- Database: Postgres

- Server config from the docker-compose file:

```
  web:
    image: alerta/alerta-web
    depends_on:
      - db
    volumes:
      - ./alerta/config.json:/web/config.json
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/monitoring
      - AUTH_REQUIRED=True
      - ADMIN_USERS=admin@alerta.io,devops@alerta.io
      - PLUGINS=reject,blackout,normalise,enhance,prometheus
      - USE_PROXYFIX=True
      - BASE_URL=/alerta
    restart: always
    networks:
      traefik_proxy:
        aliases:
          - alerta
    container_name: alerta
    labels:
      - "namespace=Monitoring"
      - "traefik.backend=alerta"
      #- "traefik.frontend.rule=Host:sub1.example.com;PathPrefix:/alerta, /config.json, /js"
      - "traefik.frontend.rule=Host:sub1.example.com;PathPrefix:/alerta"
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.passHostHeader=true"
```

**Comment by Madic-** [comment]
After analysing the downloaded javascript files I can see, that the file "app.f24b8480.js" does not contain any reference to the config.json but the app.f24b8480.js.map does. But this one does not get loaded. The .map file has also the changes from 090dac77826732d0fe48b001ba55fd105fb8a06f

**Comment by satterly** [comment]
If you want the web UI to work on a subpath you need to set the API base URL to something ending in `/api` eg. `BASE_URL=/alerta/api` will put the API on `/alerta/api` and the web UI on `/alerta`.

**Comment by Madic-** [comment]
The problem still exists. config.json gets loaded from /, e.g. sub1.example.com/config.json instead of sub1.example.com/alerta/config.json

```
  web:
    image: alerta/alerta-web
    depends_on:
      - db
    volumes:
      - ./alerta/config.json:/web/config.json
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/monitoring
      - AUTH_REQUIRED=True
      - ADMIN_USERS=admin@alerta.io,devops@alerta.io
      - PLUGINS=reject,blackout,normalise,enhance,prometheus
      - USE_PROXYFIX=True
      - BASE_URL=/alerta/api
    restart: always
    networks:
      traefik_proxy:
        aliases:
          - alerta
    container_name: alerta
    labels:
      - "namespace=Monitoring"
      - "traefik.backend=alerta"
      #- "traefik.frontend.rule=Host:sub1.example.com;PathPrefix:/alerta, /config.json, /js, /audio"
      - "traefik.frontend.rule=Host:sub1.example.com;PathPrefix:/alerta"
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.passHostHeader=true"
```
